[bumpver]
current_version = "2.1.0"
version_pattern = "MAJOR.MINOR.PATCH[-PYTAGNUM]"
commit_message = "release: {new_version}"
tag_message = "Release: {new_version}"
tag_scope = "default"
pre_commit_hook = ""
post_commit_hook = ""
commit = false
tag = false
push = false

[bumpver.file_patterns]
"README.md" = [
    "{version}"
]
"bumpver.toml" = [
    'current_version = "{version}"',
]
"charts/certs-ui/Chart.yaml" = [
    'version: {version}',
    'appVersion: "{version}"',
]
"charts/certs-ui/templates/deployment.yaml" = [
    'image: "{{ .Values.image.repository }}:{version}"',
]
