{{- if and .Values.ingress.enabled .Values.ingress.traefik }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "certs-ui.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "certs-ui.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ (index .Values.ingress.hosts 0).host }}`)
      kind: Rule
      services:
        - name: {{ include "certs-ui.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
