{{- if and .Values.ingress.enabled .Values.ingress.traefik.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "certs-ui.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "certs-ui.labels" . | nindent 4 }}
  {{- if or .Values.ingress.annotations .Values.ingress.className }}
  annotations:
    {{- if .Values.ingress.className }}
    kubernetes.io/ingress.class: {{ .Values.ingress.className | quote }}
    {{- end }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  entryPoints:
    {{- range .Values.ingress.traefik.entryPoints }}
    - {{ . | quote }}
    {{- end }}
  routes:
    - match: Host(`{{ (index .Values.ingress.hosts 0).host }}`)
      kind: Rule
      middlewares:
      services:
        - name: {{ include "certs-ui.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
